// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Arrivals arrivals
//
// swagger:model Arrivals
type Arrivals struct {

	// arrivals
	Arrivals []*Alternative `json:"arrivals"`

	// realtime data updated at
	RealtimeDataUpdatedAt float64 `json:"realtimeDataUpdatedAt,omitempty"`
}

// Validate validates this arrivals
func (m *Arrivals) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateArrivals(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Arrivals) validateArrivals(formats strfmt.Registry) error {
	if swag.IsZero(m.Arrivals) { // not required
		return nil
	}

	for i := 0; i < len(m.Arrivals); i++ {
		if swag.IsZero(m.Arrivals[i]) { // not required
			continue
		}

		if m.Arrivals[i] != nil {
			if err := m.Arrivals[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("arrivals" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("arrivals" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this arrivals based on the context it is used
func (m *Arrivals) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateArrivals(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Arrivals) contextValidateArrivals(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Arrivals); i++ {

		if m.Arrivals[i] != nil {

			if swag.IsZero(m.Arrivals[i]) { // not required
				return nil
			}

			if err := m.Arrivals[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("arrivals" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("arrivals" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Arrivals) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Arrivals) UnmarshalBinary(b []byte) error {
	var res Arrivals
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
