// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Departures departures
//
// swagger:model Departures
type Departures struct {

	// departures
	Departures []*Alternative `json:"departures"`

	// realtime data updated at
	RealtimeDataUpdatedAt float64 `json:"realtimeDataUpdatedAt,omitempty"`
}

// Validate validates this departures
func (m *Departures) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDepartures(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Departures) validateDepartures(formats strfmt.Registry) error {
	if swag.IsZero(m.Departures) { // not required
		return nil
	}

	for i := 0; i < len(m.Departures); i++ {
		if swag.IsZero(m.Departures[i]) { // not required
			continue
		}

		if m.Departures[i] != nil {
			if err := m.Departures[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("departures" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("departures" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this departures based on the context it is used
func (m *Departures) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDepartures(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Departures) contextValidateDepartures(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Departures); i++ {

		if m.Departures[i] != nil {

			if swag.IsZero(m.Departures[i]) { // not required
				return nil
			}

			if err := m.Departures[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("departures" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("departures" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Departures) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Departures) UnmarshalBinary(b []byte) error {
	var res Departures
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
