// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeparturesArrivalsOptions departures arrivals options
//
// swagger:model DeparturesArrivalsOptions
type DeparturesArrivalsOptions struct {

	// only show departures heading to this station
	Direction *string `json:"direction,omitempty"`

	// show departures for the next n minutes
	Duration *float64 `json:"duration,omitempty"`

	// parse & expose entrances of stops/stations?
	Entrances *bool `json:"entrances,omitempty"`

	// departures at related stations
	IncludeRelatedStations *bool `json:"includeRelatedStations,omitempty"`

	// language
	Language *string `json:"language,omitempty"`

	// filter by line ID
	Line *string `json:"line,omitempty"`

	// parse & expose lines at the stop/station?
	LinesOfStops *bool `json:"linesOfStops,omitempty"`

	// products
	Products Products `json:"products,omitempty"`

	// parse & expose hints & warnings?
	Remarks *bool `json:"remarks,omitempty"`

	// max. number of results; `null` means "whatever HAFAS wants"
	Results *float64 `json:"results,omitempty"`

	// fetch & parse previous/next stopovers?
	Stopovers *bool `json:"stopovers,omitempty"`

	// parse & expose sub-stops of stations?
	SubStops *bool `json:"subStops,omitempty"`

	// departure date, undefined corresponds to Date.Now
	When *string `json:"when,omitempty"`
}

// Validate validates this departures arrivals options
func (m *DeparturesArrivalsOptions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProducts(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeparturesArrivalsOptions) validateProducts(formats strfmt.Registry) error {
	if swag.IsZero(m.Products) { // not required
		return nil
	}

	if m.Products != nil {
		if err := m.Products.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("products")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("products")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this departures arrivals options based on the context it is used
func (m *DeparturesArrivalsOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateProducts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeparturesArrivalsOptions) contextValidateProducts(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Products) { // not required
		return nil
	}

	if err := m.Products.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("products")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("products")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeparturesArrivalsOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeparturesArrivalsOptions) UnmarshalBinary(b []byte) error {
	var res DeparturesArrivalsOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
