// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DurationsWithRealtimeData durations with realtime data
//
// swagger:model DurationsWithRealtimeData
type DurationsWithRealtimeData struct {

	// reachable
	Reachable []*Duration `json:"reachable"`

	// realtime data updated at
	RealtimeDataUpdatedAt float64 `json:"realtimeDataUpdatedAt,omitempty"`
}

// Validate validates this durations with realtime data
func (m *DurationsWithRealtimeData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReachable(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DurationsWithRealtimeData) validateReachable(formats strfmt.Registry) error {
	if swag.IsZero(m.Reachable) { // not required
		return nil
	}

	for i := 0; i < len(m.Reachable); i++ {
		if swag.IsZero(m.Reachable[i]) { // not required
			continue
		}

		if m.Reachable[i] != nil {
			if err := m.Reachable[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("reachable" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("reachable" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this durations with realtime data based on the context it is used
func (m *DurationsWithRealtimeData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateReachable(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DurationsWithRealtimeData) contextValidateReachable(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Reachable); i++ {

		if m.Reachable[i] != nil {

			if swag.IsZero(m.Reachable[i]) { // not required
				return nil
			}

			if err := m.Reachable[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("reachable" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("reachable" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DurationsWithRealtimeData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DurationsWithRealtimeData) UnmarshalBinary(b []byte) error {
	var res DurationsWithRealtimeData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
