// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Facilities facilities
//
// swagger:model Facilities
type Facilities map[string]string

// Validate validates this facilities
func (m Facilities) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this facilities based on context it is used
func (m Facilities) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
