// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LinesOptions lines options
//
// swagger:model LinesOptions
type LinesOptions struct {

	// Language of the results
	Language *string `json:"language,omitempty"`
}

// Validate validates this lines options
func (m *LinesOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this lines options based on context it is used
func (m *LinesOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LinesOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LinesOptions) UnmarshalBinary(b []byte) error {
	var res LinesOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
