// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Radar radar
//
// swagger:model Radar
type Radar struct {

	// movements
	Movements []*Movement `json:"movements"`

	// realtime data updated at
	RealtimeDataUpdatedAt float64 `json:"realtimeDataUpdatedAt,omitempty"`
}

// Validate validates this radar
func (m *Radar) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMovements(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Radar) validateMovements(formats strfmt.Registry) error {
	if swag.IsZero(m.Movements) { // not required
		return nil
	}

	for i := 0; i < len(m.Movements); i++ {
		if swag.IsZero(m.Movements[i]) { // not required
			continue
		}

		if m.Movements[i] != nil {
			if err := m.Movements[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("movements" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("movements" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this radar based on the context it is used
func (m *Radar) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMovements(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Radar) contextValidateMovements(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Movements); i++ {

		if m.Movements[i] != nil {

			if swag.IsZero(m.Movements[i]) { // not required
				return nil
			}

			if err := m.Movements[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("movements" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("movements" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Radar) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Radar) UnmarshalBinary(b []byte) error {
	var res Radar
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
