// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ScheduledDays scheduled days
//
// swagger:model ScheduledDays
type ScheduledDays map[string]bool

// Validate validates this scheduled days
func (m ScheduledDays) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this scheduled days based on context it is used
func (m ScheduledDays) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
