// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Station A station is a larger building or area that can be identified by a name.
// It is usually represented by a single node on a public transport map.
// Whereas a stop usually specifies a location, a station often is a broader area
// that may span across multiple levels or buildings.
//
// swagger:model Station
type Station struct {

	// distance
	Distance float64 `json:"distance,omitempty"`

	// entrances
	Entrances []*Location `json:"entrances"`

	// facilities
	Facilities Facilities `json:"facilities,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// is meta
	IsMeta bool `json:"isMeta,omitempty"`

	// lines
	Lines []*Line `json:"lines"`

	// location
	Location *Location `json:"location,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// products
	Products Products `json:"products,omitempty"`

	// region ids
	Regions []string `json:"regions"`

	// reisezentrum opening hours
	ReisezentrumOpeningHours *ReisezentrumOpeningHours `json:"reisezentrumOpeningHours,omitempty"`

	// station
	Station *Station `json:"station,omitempty"`

	// stops
	Stops []*Stop `json:"stops"`

	// transit authority
	TransitAuthority string `json:"transitAuthority,omitempty"`

	// type
	// Enum: ["station"]
	Type string `json:"type,omitempty"`
}

// Validate validates this station
func (m *Station) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEntrances(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFacilities(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLines(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLocation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProducts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReisezentrumOpeningHours(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStops(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Station) validateEntrances(formats strfmt.Registry) error {
	if swag.IsZero(m.Entrances) { // not required
		return nil
	}

	for i := 0; i < len(m.Entrances); i++ {
		if swag.IsZero(m.Entrances[i]) { // not required
			continue
		}

		if m.Entrances[i] != nil {
			if err := m.Entrances[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("entrances" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("entrances" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Station) validateFacilities(formats strfmt.Registry) error {
	if swag.IsZero(m.Facilities) { // not required
		return nil
	}

	if m.Facilities != nil {
		if err := m.Facilities.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("facilities")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("facilities")
			}
			return err
		}
	}

	return nil
}

func (m *Station) validateLines(formats strfmt.Registry) error {
	if swag.IsZero(m.Lines) { // not required
		return nil
	}

	for i := 0; i < len(m.Lines); i++ {
		if swag.IsZero(m.Lines[i]) { // not required
			continue
		}

		if m.Lines[i] != nil {
			if err := m.Lines[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("lines" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("lines" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Station) validateLocation(formats strfmt.Registry) error {
	if swag.IsZero(m.Location) { // not required
		return nil
	}

	if m.Location != nil {
		if err := m.Location.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("location")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("location")
			}
			return err
		}
	}

	return nil
}

func (m *Station) validateProducts(formats strfmt.Registry) error {
	if swag.IsZero(m.Products) { // not required
		return nil
	}

	if m.Products != nil {
		if err := m.Products.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("products")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("products")
			}
			return err
		}
	}

	return nil
}

func (m *Station) validateReisezentrumOpeningHours(formats strfmt.Registry) error {
	if swag.IsZero(m.ReisezentrumOpeningHours) { // not required
		return nil
	}

	if m.ReisezentrumOpeningHours != nil {
		if err := m.ReisezentrumOpeningHours.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("reisezentrumOpeningHours")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("reisezentrumOpeningHours")
			}
			return err
		}
	}

	return nil
}

func (m *Station) validateStation(formats strfmt.Registry) error {
	if swag.IsZero(m.Station) { // not required
		return nil
	}

	if m.Station != nil {
		if err := m.Station.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("station")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("station")
			}
			return err
		}
	}

	return nil
}

func (m *Station) validateStops(formats strfmt.Registry) error {
	if swag.IsZero(m.Stops) { // not required
		return nil
	}

	for i := 0; i < len(m.Stops); i++ {
		if swag.IsZero(m.Stops[i]) { // not required
			continue
		}

		if m.Stops[i] != nil {
			if err := m.Stops[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("stops" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("stops" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var stationTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["station"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		stationTypeTypePropEnum = append(stationTypeTypePropEnum, v)
	}
}

const (

	// StationTypeStation captures enum value "station"
	StationTypeStation string = "station"
)

// prop value enum
func (m *Station) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, stationTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Station) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this station based on the context it is used
func (m *Station) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEntrances(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFacilities(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLines(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLocation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProducts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateReisezentrumOpeningHours(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStops(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Station) contextValidateEntrances(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Entrances); i++ {

		if m.Entrances[i] != nil {

			if swag.IsZero(m.Entrances[i]) { // not required
				return nil
			}

			if err := m.Entrances[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("entrances" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("entrances" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Station) contextValidateFacilities(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Facilities) { // not required
		return nil
	}

	if err := m.Facilities.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("facilities")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("facilities")
		}
		return err
	}

	return nil
}

func (m *Station) contextValidateLines(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Lines); i++ {

		if m.Lines[i] != nil {

			if swag.IsZero(m.Lines[i]) { // not required
				return nil
			}

			if err := m.Lines[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("lines" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("lines" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Station) contextValidateLocation(ctx context.Context, formats strfmt.Registry) error {

	if m.Location != nil {

		if swag.IsZero(m.Location) { // not required
			return nil
		}

		if err := m.Location.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("location")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("location")
			}
			return err
		}
	}

	return nil
}

func (m *Station) contextValidateProducts(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Products) { // not required
		return nil
	}

	if err := m.Products.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("products")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("products")
		}
		return err
	}

	return nil
}

func (m *Station) contextValidateReisezentrumOpeningHours(ctx context.Context, formats strfmt.Registry) error {

	if m.ReisezentrumOpeningHours != nil {

		if swag.IsZero(m.ReisezentrumOpeningHours) { // not required
			return nil
		}

		if err := m.ReisezentrumOpeningHours.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("reisezentrumOpeningHours")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("reisezentrumOpeningHours")
			}
			return err
		}
	}

	return nil
}

func (m *Station) contextValidateStation(ctx context.Context, formats strfmt.Registry) error {

	if m.Station != nil {

		if swag.IsZero(m.Station) { // not required
			return nil
		}

		if err := m.Station.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("station")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("station")
			}
			return err
		}
	}

	return nil
}

func (m *Station) contextValidateStops(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Stops); i++ {

		if m.Stops[i] != nil {

			if swag.IsZero(m.Stops[i]) { // not required
				return nil
			}

			if err := m.Stops[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("stops" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("stops" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Station) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Station) UnmarshalBinary(b []byte) error {
	var res Station
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
