// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Status status
//
// swagger:model Status
type Status struct {

	// code
	Code string `json:"code,omitempty"`

	// summary
	Summary string `json:"summary,omitempty"`

	// text
	Text string `json:"text,omitempty"`

	// trip Id
	TripID string `json:"tripId,omitempty"`

	// type
	// Enum: ["foreign-id","hint","local-fare-zone","status","stop-dhid","stop-website","transit-authority"]
	Type string `json:"type,omitempty"`
}

// Validate validates this status
func (m *Status) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var statusTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["foreign-id","hint","local-fare-zone","status","stop-dhid","stop-website","transit-authority"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		statusTypeTypePropEnum = append(statusTypeTypePropEnum, v)
	}
}

const (

	// StatusTypeForeignDashID captures enum value "foreign-id"
	StatusTypeForeignDashID string = "foreign-id"

	// StatusTypeHint captures enum value "hint"
	StatusTypeHint string = "hint"

	// StatusTypeLocalDashFareDashZone captures enum value "local-fare-zone"
	StatusTypeLocalDashFareDashZone string = "local-fare-zone"

	// StatusTypeStatus captures enum value "status"
	StatusTypeStatus string = "status"

	// StatusTypeStopDashDhid captures enum value "stop-dhid"
	StatusTypeStopDashDhid string = "stop-dhid"

	// StatusTypeStopDashWebsite captures enum value "stop-website"
	StatusTypeStopDashWebsite string = "stop-website"

	// StatusTypeTransitDashAuthority captures enum value "transit-authority"
	StatusTypeTransitDashAuthority string = "transit-authority"
)

// prop value enum
func (m *Status) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, statusTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Status) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this status based on context it is used
func (m *Status) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Status) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Status) UnmarshalBinary(b []byte) error {
	var res Status
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
