// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StopOptions stop options
//
// swagger:model StopOptions
type StopOptions struct {

	// parse & expose entrances of stops/stations?
	Entrances *bool `json:"entrances,omitempty"`

	// Language of the results
	Language *string `json:"language,omitempty"`

	// parse & expose lines at the stop/station?
	LinesOfStops *bool `json:"linesOfStops,omitempty"`

	// parse & expose hints & warnings?
	Remarks *bool `json:"remarks,omitempty"`

	// parse & expose sub-stops of stations?
	SubStops *bool `json:"subStops,omitempty"`
}

// Validate validates this stop options
func (m *StopOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this stop options based on context it is used
func (m *StopOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StopOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StopOptions) UnmarshalBinary(b []byte) error {
	var res StopOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
