// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetStationsIDParams creates a new GetStationsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetStationsIDParams() *GetStationsIDParams {
	return &GetStationsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetStationsIDParamsWithTimeout creates a new GetStationsIDParams object
// with the ability to set a timeout on a request.
func NewGetStationsIDParamsWithTimeout(timeout time.Duration) *GetStationsIDParams {
	return &GetStationsIDParams{
		timeout: timeout,
	}
}

// NewGetStationsIDParamsWithContext creates a new GetStationsIDParams object
// with the ability to set a context for a request.
func NewGetStationsIDParamsWithContext(ctx context.Context) *GetStationsIDParams {
	return &GetStationsIDParams{
		Context: ctx,
	}
}

// NewGetStationsIDParamsWithHTTPClient creates a new GetStationsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetStationsIDParamsWithHTTPClient(client *http.Client) *GetStationsIDParams {
	return &GetStationsIDParams{
		HTTPClient: client,
	}
}

/* GetStationsIDParams contains all the parameters to send to the API endpoint
   for the get stations ID operation.

   Typically these are written to a http.Request.
*/
type GetStationsIDParams struct {

	/* ID.

	   Stop/station ID.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get stations ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStationsIDParams) WithDefaults() *GetStationsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get stations ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStationsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get stations ID params
func (o *GetStationsIDParams) WithTimeout(timeout time.Duration) *GetStationsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get stations ID params
func (o *GetStationsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get stations ID params
func (o *GetStationsIDParams) WithContext(ctx context.Context) *GetStationsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get stations ID params
func (o *GetStationsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get stations ID params
func (o *GetStationsIDParams) WithHTTPClient(client *http.Client) *GetStationsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get stations ID params
func (o *GetStationsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get stations ID params
func (o *GetStationsIDParams) WithID(id string) *GetStationsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get stations ID params
func (o *GetStationsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetStationsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
