// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"traines.eu/time-space-train-planner/providers/dbrest/models"
)

// GetStopsIDDeparturesReader is a Reader for the GetStopsIDDepartures structure.
type GetStopsIDDeparturesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStopsIDDeparturesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStopsIDDeparturesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetStopsIDDeparturesOK creates a GetStopsIDDeparturesOK with default headers values
func NewGetStopsIDDeparturesOK() *GetStopsIDDeparturesOK {
	return &GetStopsIDDeparturesOK{}
}

/* GetStopsIDDeparturesOK describes a response with status code 200, with default header values.

An array of departures, in the [`hafas-client` format](https://github.com/public-transport/hafas-client/blob/5/docs/departures.md).
*/
type GetStopsIDDeparturesOK struct {
	Payload []*models.DepartureArrival
}

func (o *GetStopsIDDeparturesOK) Error() string {
	return fmt.Sprintf("[GET /stops/{id}/departures][%d] getStopsIdDeparturesOK  %+v", 200, o.Payload)
}
func (o *GetStopsIDDeparturesOK) GetPayload() []*models.DepartureArrival {
	return o.Payload
}

func (o *GetStopsIDDeparturesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
