// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetStopsIDDeparturesParams creates a new GetStopsIDDeparturesParams object
// with the default values initialized.
func NewGetStopsIDDeparturesParams() *GetStopsIDDeparturesParams {
	var (
		durationDefault     = int64(10)
		languageDefault     = string("en")
		linesOfStopsDefault = bool(false)
		remarksDefault      = bool(true)
	)
	return &GetStopsIDDeparturesParams{
		Duration:     &durationDefault,
		Language:     &languageDefault,
		LinesOfStops: &linesOfStopsDefault,
		Remarks:      &remarksDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStopsIDDeparturesParamsWithTimeout creates a new GetStopsIDDeparturesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStopsIDDeparturesParamsWithTimeout(timeout time.Duration) *GetStopsIDDeparturesParams {
	var (
		durationDefault     = int64(10)
		languageDefault     = string("en")
		linesOfStopsDefault = bool(false)
		remarksDefault      = bool(true)
	)
	return &GetStopsIDDeparturesParams{
		Duration:     &durationDefault,
		Language:     &languageDefault,
		LinesOfStops: &linesOfStopsDefault,
		Remarks:      &remarksDefault,

		timeout: timeout,
	}
}

// NewGetStopsIDDeparturesParamsWithContext creates a new GetStopsIDDeparturesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStopsIDDeparturesParamsWithContext(ctx context.Context) *GetStopsIDDeparturesParams {
	var (
		durationDefault     = int64(10)
		languageDefault     = string("en")
		linesOfStopsDefault = bool(false)
		remarksDefault      = bool(true)
	)
	return &GetStopsIDDeparturesParams{
		Duration:     &durationDefault,
		Language:     &languageDefault,
		LinesOfStops: &linesOfStopsDefault,
		Remarks:      &remarksDefault,

		Context: ctx,
	}
}

// NewGetStopsIDDeparturesParamsWithHTTPClient creates a new GetStopsIDDeparturesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStopsIDDeparturesParamsWithHTTPClient(client *http.Client) *GetStopsIDDeparturesParams {
	var (
		durationDefault     = int64(10)
		languageDefault     = string("en")
		linesOfStopsDefault = bool(false)
		remarksDefault      = bool(true)
	)
	return &GetStopsIDDeparturesParams{
		Duration:     &durationDefault,
		Language:     &languageDefault,
		LinesOfStops: &linesOfStopsDefault,
		Remarks:      &remarksDefault,
		HTTPClient:   client,
	}
}

/*GetStopsIDDeparturesParams contains all the parameters to send to the API endpoint
for the get stops ID departures operation typically these are written to a http.Request
*/
type GetStopsIDDeparturesParams struct {

	/*Direction
	  Filter departures by direction.

	*/
	Direction *string
	/*Duration
	  Show departures for how many minutes?

	*/
	Duration *int64
	/*ID
	  stop/station ID to show departures for

	*/
	ID string
	/*Language
	  Language of the results.

	*/
	Language *string
	/*LinesOfStops
	  Parse & return lines of each stop/station?

	*/
	LinesOfStops *bool
	/*Remarks
	  Parse & return hints & warnings?

	*/
	Remarks *bool
	/*Results
	  Max. number of departures. – Default: *whatever HAFAS wants

	*/
	Results *int64
	/*When
	  Date & time to get departures for. – Default: *now*

	*/
	When *strfmt.DateTime

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) WithTimeout(timeout time.Duration) *GetStopsIDDeparturesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) WithContext(ctx context.Context) *GetStopsIDDeparturesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) WithHTTPClient(client *http.Client) *GetStopsIDDeparturesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDirection adds the direction to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) WithDirection(direction *string) *GetStopsIDDeparturesParams {
	o.SetDirection(direction)
	return o
}

// SetDirection adds the direction to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) SetDirection(direction *string) {
	o.Direction = direction
}

// WithDuration adds the duration to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) WithDuration(duration *int64) *GetStopsIDDeparturesParams {
	o.SetDuration(duration)
	return o
}

// SetDuration adds the duration to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) SetDuration(duration *int64) {
	o.Duration = duration
}

// WithID adds the id to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) WithID(id string) *GetStopsIDDeparturesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) SetID(id string) {
	o.ID = id
}

// WithLanguage adds the language to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) WithLanguage(language *string) *GetStopsIDDeparturesParams {
	o.SetLanguage(language)
	return o
}

// SetLanguage adds the language to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) SetLanguage(language *string) {
	o.Language = language
}

// WithLinesOfStops adds the linesOfStops to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) WithLinesOfStops(linesOfStops *bool) *GetStopsIDDeparturesParams {
	o.SetLinesOfStops(linesOfStops)
	return o
}

// SetLinesOfStops adds the linesOfStops to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) SetLinesOfStops(linesOfStops *bool) {
	o.LinesOfStops = linesOfStops
}

// WithRemarks adds the remarks to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) WithRemarks(remarks *bool) *GetStopsIDDeparturesParams {
	o.SetRemarks(remarks)
	return o
}

// SetRemarks adds the remarks to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) SetRemarks(remarks *bool) {
	o.Remarks = remarks
}

// WithResults adds the results to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) WithResults(results *int64) *GetStopsIDDeparturesParams {
	o.SetResults(results)
	return o
}

// SetResults adds the results to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) SetResults(results *int64) {
	o.Results = results
}

// WithWhen adds the when to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) WithWhen(when *strfmt.DateTime) *GetStopsIDDeparturesParams {
	o.SetWhen(when)
	return o
}

// SetWhen adds the when to the get stops ID departures params
func (o *GetStopsIDDeparturesParams) SetWhen(when *strfmt.DateTime) {
	o.When = when
}

// WriteToRequest writes these params to a swagger request
func (o *GetStopsIDDeparturesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Direction != nil {

		// query param direction
		var qrDirection string
		if o.Direction != nil {
			qrDirection = *o.Direction
		}
		qDirection := qrDirection
		if qDirection != "" {
			if err := r.SetQueryParam("direction", qDirection); err != nil {
				return err
			}
		}

	}

	if o.Duration != nil {

		// query param duration
		var qrDuration int64
		if o.Duration != nil {
			qrDuration = *o.Duration
		}
		qDuration := swag.FormatInt64(qrDuration)
		if qDuration != "" {
			if err := r.SetQueryParam("duration", qDuration); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Language != nil {

		// query param language
		var qrLanguage string
		if o.Language != nil {
			qrLanguage = *o.Language
		}
		qLanguage := qrLanguage
		if qLanguage != "" {
			if err := r.SetQueryParam("language", qLanguage); err != nil {
				return err
			}
		}

	}

	if o.LinesOfStops != nil {

		// query param linesOfStops
		var qrLinesOfStops bool
		if o.LinesOfStops != nil {
			qrLinesOfStops = *o.LinesOfStops
		}
		qLinesOfStops := swag.FormatBool(qrLinesOfStops)
		if qLinesOfStops != "" {
			if err := r.SetQueryParam("linesOfStops", qLinesOfStops); err != nil {
				return err
			}
		}

	}

	if o.Remarks != nil {

		// query param remarks
		var qrRemarks bool
		if o.Remarks != nil {
			qrRemarks = *o.Remarks
		}
		qRemarks := swag.FormatBool(qrRemarks)
		if qRemarks != "" {
			if err := r.SetQueryParam("remarks", qRemarks); err != nil {
				return err
			}
		}

	}

	if o.Results != nil {

		// query param results
		var qrResults int64
		if o.Results != nil {
			qrResults = *o.Results
		}
		qResults := swag.FormatInt64(qrResults)
		if qResults != "" {
			if err := r.SetQueryParam("results", qResults); err != nil {
				return err
			}
		}

	}

	if o.When != nil {

		// query param when
		var qrWhen strfmt.DateTime
		if o.When != nil {
			qrWhen = *o.When
		}
		qWhen := qrWhen.String()
		if qWhen != "" {
			if err := r.SetQueryParam("when", qWhen); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
