// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"traines.eu/time-space-train-planner/providers/dbrest/models"
)

// GetStopsIDArrivalsReader is a Reader for the GetStopsIDArrivals structure.
type GetStopsIDArrivalsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStopsIDArrivalsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStopsIDArrivalsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetStopsIDArrivalsOK creates a GetStopsIDArrivalsOK with default headers values
func NewGetStopsIDArrivalsOK() *GetStopsIDArrivalsOK {
	return &GetStopsIDArrivalsOK{}
}

/* GetStopsIDArrivalsOK describes a response with status code 200, with default header values.

An array of arrivals, in the [`hafas-client` format](https://github.com/public-transport/hafas-client/blob/5/docs/arrivals.md).
*/
type GetStopsIDArrivalsOK struct {
	Payload []*models.DepartureArrival
}

func (o *GetStopsIDArrivalsOK) Error() string {
	return fmt.Sprintf("[GET /stops/{id}/arrivals][%d] getStopsIdArrivalsOK  %+v", 200, o.Payload)
}
func (o *GetStopsIDArrivalsOK) GetPayload() []*models.DepartureArrival {
	return o.Payload
}

func (o *GetStopsIDArrivalsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
