// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MultipleTrips A wrapper that represents multiple Trip objects.
//
// swagger:model multipleTrips
type MultipleTrips struct {

	// List of trip elements.
	Trip []*Trip `json:"trip" xml:"trip"`
}

// Validate validates this multiple trips
func (m *MultipleTrips) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTrip(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MultipleTrips) validateTrip(formats strfmt.Registry) error {

	if swag.IsZero(m.Trip) { // not required
		return nil
	}

	for i := 0; i < len(m.Trip); i++ {
		if swag.IsZero(m.Trip[i]) { // not required
			continue
		}

		if m.Trip[i] != nil {
			if err := m.Trip[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("trip" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *MultipleTrips) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MultipleTrips) UnmarshalBinary(b []byte) error {
	var res MultipleTrips
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
