// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTimetableRchgEvaNoParams creates a new GetTimetableRchgEvaNoParams object
// with the default values initialized.
func NewGetTimetableRchgEvaNoParams() *GetTimetableRchgEvaNoParams {
	var ()
	return &GetTimetableRchgEvaNoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTimetableRchgEvaNoParamsWithTimeout creates a new GetTimetableRchgEvaNoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTimetableRchgEvaNoParamsWithTimeout(timeout time.Duration) *GetTimetableRchgEvaNoParams {
	var ()
	return &GetTimetableRchgEvaNoParams{

		timeout: timeout,
	}
}

// NewGetTimetableRchgEvaNoParamsWithContext creates a new GetTimetableRchgEvaNoParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTimetableRchgEvaNoParamsWithContext(ctx context.Context) *GetTimetableRchgEvaNoParams {
	var ()
	return &GetTimetableRchgEvaNoParams{

		Context: ctx,
	}
}

// NewGetTimetableRchgEvaNoParamsWithHTTPClient creates a new GetTimetableRchgEvaNoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTimetableRchgEvaNoParamsWithHTTPClient(client *http.Client) *GetTimetableRchgEvaNoParams {
	var ()
	return &GetTimetableRchgEvaNoParams{
		HTTPClient: client,
	}
}

/*GetTimetableRchgEvaNoParams contains all the parameters to send to the API endpoint
for the get timetable rchg eva no operation typically these are written to a http.Request
*/
type GetTimetableRchgEvaNoParams struct {

	/*EvaNo
	  Station EVA-number.

	*/
	EvaNo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get timetable rchg eva no params
func (o *GetTimetableRchgEvaNoParams) WithTimeout(timeout time.Duration) *GetTimetableRchgEvaNoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get timetable rchg eva no params
func (o *GetTimetableRchgEvaNoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get timetable rchg eva no params
func (o *GetTimetableRchgEvaNoParams) WithContext(ctx context.Context) *GetTimetableRchgEvaNoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get timetable rchg eva no params
func (o *GetTimetableRchgEvaNoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get timetable rchg eva no params
func (o *GetTimetableRchgEvaNoParams) WithHTTPClient(client *http.Client) *GetTimetableRchgEvaNoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get timetable rchg eva no params
func (o *GetTimetableRchgEvaNoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEvaNo adds the evaNo to the get timetable rchg eva no params
func (o *GetTimetableRchgEvaNoParams) WithEvaNo(evaNo string) *GetTimetableRchgEvaNoParams {
	o.SetEvaNo(evaNo)
	return o
}

// SetEvaNo adds the evaNo to the get timetable rchg eva no params
func (o *GetTimetableRchgEvaNoParams) SetEvaNo(evaNo string) {
	o.EvaNo = evaNo
}

// WriteToRequest writes these params to a swagger request
func (o *GetTimetableRchgEvaNoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param evaNo
	if err := r.SetPathParam("evaNo", o.EvaNo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
