// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetFchgEvaNoParams creates a new GetFchgEvaNoParams object
// with the default values initialized.
func NewGetFchgEvaNoParams() *GetFchgEvaNoParams {
	var ()
	return &GetFchgEvaNoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFchgEvaNoParamsWithTimeout creates a new GetFchgEvaNoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFchgEvaNoParamsWithTimeout(timeout time.Duration) *GetFchgEvaNoParams {
	var ()
	return &GetFchgEvaNoParams{

		timeout: timeout,
	}
}

// NewGetFchgEvaNoParamsWithContext creates a new GetFchgEvaNoParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFchgEvaNoParamsWithContext(ctx context.Context) *GetFchgEvaNoParams {
	var ()
	return &GetFchgEvaNoParams{

		Context: ctx,
	}
}

// NewGetFchgEvaNoParamsWithHTTPClient creates a new GetFchgEvaNoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFchgEvaNoParamsWithHTTPClient(client *http.Client) *GetFchgEvaNoParams {
	var ()
	return &GetFchgEvaNoParams{
		HTTPClient: client,
	}
}

/*GetFchgEvaNoParams contains all the parameters to send to the API endpoint
for the get fchg eva no operation typically these are written to a http.Request
*/
type GetFchgEvaNoParams struct {

	/*EvaNo
	  Station EVA-number.

	*/
	EvaNo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get fchg eva no params
func (o *GetFchgEvaNoParams) WithTimeout(timeout time.Duration) *GetFchgEvaNoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get fchg eva no params
func (o *GetFchgEvaNoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get fchg eva no params
func (o *GetFchgEvaNoParams) WithContext(ctx context.Context) *GetFchgEvaNoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get fchg eva no params
func (o *GetFchgEvaNoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get fchg eva no params
func (o *GetFchgEvaNoParams) WithHTTPClient(client *http.Client) *GetFchgEvaNoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get fchg eva no params
func (o *GetFchgEvaNoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEvaNo adds the evaNo to the get fchg eva no params
func (o *GetFchgEvaNoParams) WithEvaNo(evaNo string) *GetFchgEvaNoParams {
	o.SetEvaNo(evaNo)
	return o
}

// SetEvaNo adds the evaNo to the get fchg eva no params
func (o *GetFchgEvaNoParams) SetEvaNo(evaNo string) {
	o.EvaNo = evaNo
}

// WriteToRequest writes these params to a swagger request
func (o *GetFchgEvaNoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param evaNo
	if err := r.SetPathParam("evaNo", o.EvaNo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
