// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"traines.eu/time-space-train-planner/providers/dbtimetables/models"
)

// GetStationPatternReader is a Reader for the GetStationPattern structure.
type GetStationPatternReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStationPatternReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStationPatternOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetStationPatternNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetStationPatternOK creates a GetStationPatternOK with default headers values
func NewGetStationPatternOK() *GetStationPatternOK {
	return &GetStationPatternOK{}
}

/*GetStationPatternOK handles this case with default header values.

successful operation
*/
type GetStationPatternOK struct {
	Payload *models.MultipleStationData
}

func (o *GetStationPatternOK) Error() string {
	return fmt.Sprintf("[GET /station/{pattern}][%d] getStationPatternOK  %+v", 200, o.Payload)
}

func (o *GetStationPatternOK) GetPayload() *models.MultipleStationData {
	return o.Payload
}

func (o *GetStationPatternOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MultipleStationData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStationPatternNotFound creates a GetStationPatternNotFound with default headers values
func NewGetStationPatternNotFound() *GetStationPatternNotFound {
	return &GetStationPatternNotFound{}
}

/*GetStationPatternNotFound handles this case with default header values.

resource not found
*/
type GetStationPatternNotFound struct {
}

func (o *GetStationPatternNotFound) Error() string {
	return fmt.Sprintf("[GET /station/{pattern}][%d] getStationPatternNotFound ", 404)
}

func (o *GetStationPatternNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
