// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HistoricPlatformChange It's the history of all platform-changes for a stop. This element extends HistoricChange.
//
// swagger:model historicPlatformChange
type HistoricPlatformChange struct {

	// Arrival platform.
	Ar string `json:"ar,omitempty" xml:"ar,attr,omitempty"`

	// Detailed cause of track change.
	Cot string `json:"cot,omitempty" xml:"cot,attr,omitempty"`

	// Departure platform.
	Dp string `json:"dp,omitempty" xml:"dp,attr,omitempty"`

	// Timestamp. The time, in ten digit 'YYMMddHHmm' format, e.g. '1404011437' for 14:37 on April the 1st of 2014.
	Ts string `json:"ts,omitempty" xml:"ts,attr,omitempty"`
}

// Validate validates this historic platform change
func (m *HistoricPlatformChange) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HistoricPlatformChange) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HistoricPlatformChange) UnmarshalBinary(b []byte) error {
	var res HistoricPlatformChange
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
