// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MultipleStationData A wrapper that represents multiple StationData objects.
//
// swagger:model multipleStationData
type MultipleStationData struct {

	// List of stations with additional data.
	// Required: true
	Station []*StationData `json:"station"`
}

// Validate validates this multiple station data
func (m *MultipleStationData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStation(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MultipleStationData) validateStation(formats strfmt.Registry) error {

	if err := validate.Required("station", "body", m.Station); err != nil {
		return err
	}

	for i := 0; i < len(m.Station); i++ {
		if swag.IsZero(m.Station[i]) { // not required
			continue
		}

		if m.Station[i] != nil {
			if err := m.Station[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("station" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *MultipleStationData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MultipleStationData) UnmarshalBinary(b []byte) error {
	var res MultipleStationData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
