// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Priority Priority.
//
// * 1 - HIGH
// * 2 - MEDIUM
// * 3 - LOW
// * 4 - DONE
//
//
// swagger:model priority
type Priority int64

// for schema
var priorityEnum []interface{}

func init() {
	var res []Priority
	if err := json.Unmarshal([]byte(`[1,2,3,4]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		priorityEnum = append(priorityEnum, v)
	}
}

func (m Priority) validatePriorityEnum(path, location string, value Priority) error {
	if err := validate.Enum(path, location, value, priorityEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this priority
func (m Priority) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validatePriorityEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
